spring:
  application:
    name: CONFIG-DEV

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true  #Default value is also true
    service-url:
      defaultZone: http://localhost:8761/eureka/



  
